import Head from "next/head";
import Header from "../components/Header";
import Hero from "../components/Hero";
import About from "../components/About";
import Skills from "../components/Skills";
import Projects from "../components/Projects";
import Contact from "../components/Contact";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Jay Dampitan</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <section id="/" className="">
        <Hero />
      </section>

      <section id="skills" className="">
        <Skills />
      </section>

      <section id="about" className="">
        <About />
      </section>

      <section id="projects" className="">
        <Projects />
      </section>

      <section id="contact" className="">
        <Contact />
      </section>

      <section id="footer" className="">
        <Footer />
      </section>
    </>
  );
}
